name: mood_swing
description: An AI-driven music recommendation system.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.7.1"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  convex_bottom_bar: ^3.0.0
  firebase_core: ^2.7.0
  cloud_functions: ^4.0.11
  google_fonts: ^2.1.0
  firebase_auth: ^4.2.6
  mediaquery_sizer: ^1.1.0
  camera: ^0.10.3
  video_player: ^2.5.1
  pin_code_fields: ^7.4.0
  animations: ^2.0.7
  collapsible_sidebar: ^2.0.3+2
  sidebarx: ^0.14.0
  easy_stepper: ^0.3.1
  simple_ripple_animation: ^0.0.7
  flutter_login: ^4.1.1
  firebase_crashlytics: ^3.0.14
  firebase_storage: ^11.0.14
  cloud_firestore: ^4.4.2
  form_field_validator: ^1.1.0
  simple_animations: ^4.0.0
  path_provider: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.10.0"
  provider: ^6.0.5
  mockito: ^5.3.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/music_swing_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/music_swing_logo.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"

flutter:
  uses-material-design: true
  fonts:
    - family: Share Tech
      fonts:
        - asset: fonts/ShareTech-Regular.ttf
    - family: Maven Pro
      fonts:
        - asset: fonts/MavenPro-Regular.ttf
        - asset: fonts/MavenPro-Bold.ttf
        - asset: fonts/MavenPro-ExtraBold.ttf
        - asset: fonts/MavenPro-Medium.ttf
        - asset: fonts/MavenPro-Black.ttf
        - asset: fonts/MavenPro-SemiBold.ttf
        - asset: fonts/MavenPro-VariableFont_wght.ttf
  assets:
    - assets/