name: mood_swing
description: An AI-driven music recommendation system.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.7.1"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  convex_bottom_bar: ^3.0.0
  firebase_core: ^2.4.1
  google_fonts: ^2.1.0
  firebase_core: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.10.0"
  provider: ^6.0.5
  mockito: ^5.3.2

flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/music_swing_logo.png"
    min_sdk_android: 21 # android min sdk min:16, default 21
    web:
      generate: true
      image_path: "assets/music_swing_logo.png"
      background_color: "#ffffff"
      theme_color: "#ffffff"

flutter:
  uses-material-design: true
  fonts:
    - family: Share Tech
      fonts:
        - asset: fonts/ShareTech-Regular.ttf
    - family: Maven Pro
      fonts:
        - asset: fonts/MavenPro-Regular.ttf
        - asset: fonts/MavenPro-Bold.ttf
        - asset: fonts/MavenPro-ExtraBold.ttf
        - asset: fonts/MavenPro-Medium.ttf
        - asset: fonts/MavenPro-Black.ttf
        - asset: fonts/MavenPro-SemiBold.ttf
        - asset: fonts/MavenPro-VariableFont_wght.ttf

assets:
  - assets/bokeh_lights.png
  - assets/music_swing_logo_med.png