// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD48WvFismpS-zdWX19Zz5kgPPwBFqEYDM',
    appId: '1:1024103738297:web:97167539deb635eb0fe468',
    messagingSenderId: '1024103738297',
    projectId: 'mood-swing-6c9d0',
    authDomain: 'mood-swing-6c9d0.firebaseapp.com',
    storageBucket: 'mood-swing-6c9d0.appspot.com',
    measurementId: 'G-1Z7X3ZBQX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWxOM9r0Ulvf4d8Xi-8GtpA8ZN_BKYQSk',
    appId: '1:1024103738297:android:d026d0457c0c46e80fe468',
    messagingSenderId: '1024103738297',
    projectId: 'mood-swing-6c9d0',
    storageBucket: 'mood-swing-6c9d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj1ZUzJwkGGo_SUsi5jdDPjeYEtg9F_Jo',
    appId: '1:1024103738297:ios:9b3ce1fb7fdb67d40fe468',
    messagingSenderId: '1024103738297',
    projectId: 'mood-swing-6c9d0',
    storageBucket: 'mood-swing-6c9d0.appspot.com',
    iosClientId: '1024103738297-ikdr012sp6bbsb1s4hpglst68m36l2nk.apps.googleusercontent.com',
    iosBundleId: 'com.tempertunes.temperTunes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj1ZUzJwkGGo_SUsi5jdDPjeYEtg9F_Jo',
    appId: '1:1024103738297:ios:9b3ce1fb7fdb67d40fe468',
    messagingSenderId: '1024103738297',
    projectId: 'mood-swing-6c9d0',
    storageBucket: 'mood-swing-6c9d0.appspot.com',
    iosClientId: '1024103738297-ikdr012sp6bbsb1s4hpglst68m36l2nk.apps.googleusercontent.com',
    iosBundleId: 'com.tempertunes.temperTunes',
  );
}
