/// Flutter icons GenerationIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GenerationIcons
///      fonts:
///       - asset: fonts/GenerationIcons.ttf
///

import 'package:flutter/widgets.dart';

class GenerationIcons {
  GenerationIcons._();

  static const _kFontFam = 'GenerationIcons';
  static const String? _kFontPkg = null;

  static const IconData cameraonly =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData neither =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData both =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sensoronly =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
